version: 0.2

phases:
  install:
    commands:
      - echo Entering the install phase...
      - ls
  pre_build:
    commands:
      - echo pre_build phase...
  build:
    commands:
      - echo build...
      - echo "shit tests failed..."; exit 1
